/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DocxExportPreviewRouteImport } from './routes/docx-export-preview'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as SidebarRouteImport } from './routes/_sidebar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SidebarHomeRouteImport } from './routes/_sidebar/home'
import { Route as SidebarTemplatesIndexRouteImport } from './routes/_sidebar/templates/index'
import { Route as SidebarTemplateVariablesIndexRouteImport } from './routes/_sidebar/template-variables/index'
import { Route as SidebarTemplateVariableDocsIndexRouteImport } from './routes/_sidebar/template-variable-docs/index'
import { Route as SidebarTemplateAgentIndexRouteImport } from './routes/_sidebar/template-agent/index'
import { Route as SidebarSettingsIndexRouteImport } from './routes/_sidebar/settings/index'
import { Route as SidebarOpenaiIndexRouteImport } from './routes/_sidebar/openai/index'
import { Route as SidebarDocumentsIndexRouteImport } from './routes/_sidebar/documents/index'
import { Route as SidebarDocumentInputAgentIndexRouteImport } from './routes/_sidebar/document-input-agent/index'
import { Route as SidebarDocumentInputAgentHistoryIndexRouteImport } from './routes/_sidebar/document-input-agent-history/index'
import { Route as SidebarDashboardIndexRouteImport } from './routes/_sidebar/dashboard/index'
import { Route as SidebarAdminIndexRouteImport } from './routes/_sidebar/admin/index'
import { Route as SidebarTemplatesNewRouteImport } from './routes/_sidebar/templates/new'
import { Route as SidebarTemplatesIdRouteImport } from './routes/_sidebar/templates/$id'
import { Route as SidebarTemplateVariablesTablesRouteImport } from './routes/_sidebar/template-variables/tables'
import { Route as SidebarTemplateVariablesSettingsRouteImport } from './routes/_sidebar/template-variables/settings'
import { Route as SidebarTemplateVariablesPowerpointRouteImport } from './routes/_sidebar/template-variables/powerpoint'
import { Route as SidebarTemplateVariablesNewRouteImport } from './routes/_sidebar/template-variables/new'
import { Route as SidebarTemplateVariablesImageFormRouteImport } from './routes/_sidebar/template-variables/image-form'
import { Route as SidebarTemplateVariablesHtmlContentRouteImport } from './routes/_sidebar/template-variables/html-content'
import { Route as SidebarTemplateVariablesFieldsRouteImport } from './routes/_sidebar/template-variables/fields'
import { Route as SidebarTemplateVariablesExcelRouteImport } from './routes/_sidebar/template-variables/excel'
import { Route as SidebarTemplateVariablesDocumentsRouteImport } from './routes/_sidebar/template-variables/documents'
import { Route as SidebarTemplateVariablesIdRouteImport } from './routes/_sidebar/template-variables/$id'
import { Route as SidebarTemplateVariableDocsDocIdRouteImport } from './routes/_sidebar/template-variable-docs/$docId'
import { Route as SidebarDocumentsNewRouteImport } from './routes/_sidebar/documents/new'
import { Route as SidebarDocumentsIdRouteImport } from './routes/_sidebar/documents/$id'
import { Route as SidebarDocumentInputAgentHistoryUserIdRouteImport } from './routes/_sidebar/document-input-agent-history/$userId'
import { Route as SidebarDashboardTicketsIndexRouteImport } from './routes/_sidebar/dashboard/tickets/index'
import { Route as SidebarTemplatesNewVariablesRouteImport } from './routes/_sidebar/templates/new.variables'
import { Route as SidebarTemplatesIdVariablesRouteImport } from './routes/_sidebar/templates/$id.variables'
import { Route as SidebarDocumentsIdVariablesRouteImport } from './routes/_sidebar/documents/$id.variables'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DocxExportPreviewRoute = DocxExportPreviewRouteImport.update({
  id: '/docx-export-preview',
  path: '/docx-export-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRoute = SidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarHomeRoute = SidebarHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarTemplatesIndexRoute = SidebarTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarTemplateVariablesIndexRoute =
  SidebarTemplateVariablesIndexRouteImport.update({
    id: '/template-variables/',
    path: '/template-variables/',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariableDocsIndexRoute =
  SidebarTemplateVariableDocsIndexRouteImport.update({
    id: '/template-variable-docs/',
    path: '/template-variable-docs/',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateAgentIndexRoute =
  SidebarTemplateAgentIndexRouteImport.update({
    id: '/template-agent/',
    path: '/template-agent/',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarSettingsIndexRoute = SidebarSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarOpenaiIndexRoute = SidebarOpenaiIndexRouteImport.update({
  id: '/openai/',
  path: '/openai/',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarDocumentsIndexRoute = SidebarDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarDocumentInputAgentIndexRoute =
  SidebarDocumentInputAgentIndexRouteImport.update({
    id: '/document-input-agent/',
    path: '/document-input-agent/',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarDocumentInputAgentHistoryIndexRoute =
  SidebarDocumentInputAgentHistoryIndexRouteImport.update({
    id: '/document-input-agent-history/',
    path: '/document-input-agent-history/',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarDashboardIndexRoute = SidebarDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarAdminIndexRoute = SidebarAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarTemplatesNewRoute = SidebarTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarTemplatesIdRoute = SidebarTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarTemplateVariablesTablesRoute =
  SidebarTemplateVariablesTablesRouteImport.update({
    id: '/template-variables/tables',
    path: '/template-variables/tables',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariablesSettingsRoute =
  SidebarTemplateVariablesSettingsRouteImport.update({
    id: '/template-variables/settings',
    path: '/template-variables/settings',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariablesPowerpointRoute =
  SidebarTemplateVariablesPowerpointRouteImport.update({
    id: '/template-variables/powerpoint',
    path: '/template-variables/powerpoint',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariablesNewRoute =
  SidebarTemplateVariablesNewRouteImport.update({
    id: '/template-variables/new',
    path: '/template-variables/new',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariablesImageFormRoute =
  SidebarTemplateVariablesImageFormRouteImport.update({
    id: '/template-variables/image-form',
    path: '/template-variables/image-form',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariablesHtmlContentRoute =
  SidebarTemplateVariablesHtmlContentRouteImport.update({
    id: '/template-variables/html-content',
    path: '/template-variables/html-content',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariablesFieldsRoute =
  SidebarTemplateVariablesFieldsRouteImport.update({
    id: '/template-variables/fields',
    path: '/template-variables/fields',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariablesExcelRoute =
  SidebarTemplateVariablesExcelRouteImport.update({
    id: '/template-variables/excel',
    path: '/template-variables/excel',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariablesDocumentsRoute =
  SidebarTemplateVariablesDocumentsRouteImport.update({
    id: '/template-variables/documents',
    path: '/template-variables/documents',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariablesIdRoute =
  SidebarTemplateVariablesIdRouteImport.update({
    id: '/template-variables/$id',
    path: '/template-variables/$id',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplateVariableDocsDocIdRoute =
  SidebarTemplateVariableDocsDocIdRouteImport.update({
    id: '/template-variable-docs/$docId',
    path: '/template-variable-docs/$docId',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarDocumentsNewRoute = SidebarDocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarDocumentsIdRoute = SidebarDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarDocumentInputAgentHistoryUserIdRoute =
  SidebarDocumentInputAgentHistoryUserIdRouteImport.update({
    id: '/document-input-agent-history/$userId',
    path: '/document-input-agent-history/$userId',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarDashboardTicketsIndexRoute =
  SidebarDashboardTicketsIndexRouteImport.update({
    id: '/dashboard/tickets/',
    path: '/dashboard/tickets/',
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarTemplatesNewVariablesRoute =
  SidebarTemplatesNewVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => SidebarTemplatesNewRoute,
  } as any)
const SidebarTemplatesIdVariablesRoute =
  SidebarTemplatesIdVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => SidebarTemplatesIdRoute,
  } as any)
const SidebarDocumentsIdVariablesRoute =
  SidebarDocumentsIdVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => SidebarDocumentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/docx-export-preview': typeof DocxExportPreviewRoute
  '/sign-in': typeof SignInRoute
  '/home': typeof SidebarHomeRoute
  '/document-input-agent-history/$userId': typeof SidebarDocumentInputAgentHistoryUserIdRoute
  '/documents/$id': typeof SidebarDocumentsIdRouteWithChildren
  '/documents/new': typeof SidebarDocumentsNewRoute
  '/template-variable-docs/$docId': typeof SidebarTemplateVariableDocsDocIdRoute
  '/template-variables/$id': typeof SidebarTemplateVariablesIdRoute
  '/template-variables/documents': typeof SidebarTemplateVariablesDocumentsRoute
  '/template-variables/excel': typeof SidebarTemplateVariablesExcelRoute
  '/template-variables/fields': typeof SidebarTemplateVariablesFieldsRoute
  '/template-variables/html-content': typeof SidebarTemplateVariablesHtmlContentRoute
  '/template-variables/image-form': typeof SidebarTemplateVariablesImageFormRoute
  '/template-variables/new': typeof SidebarTemplateVariablesNewRoute
  '/template-variables/powerpoint': typeof SidebarTemplateVariablesPowerpointRoute
  '/template-variables/settings': typeof SidebarTemplateVariablesSettingsRoute
  '/template-variables/tables': typeof SidebarTemplateVariablesTablesRoute
  '/templates/$id': typeof SidebarTemplatesIdRouteWithChildren
  '/templates/new': typeof SidebarTemplatesNewRouteWithChildren
  '/admin/': typeof SidebarAdminIndexRoute
  '/dashboard/': typeof SidebarDashboardIndexRoute
  '/document-input-agent-history/': typeof SidebarDocumentInputAgentHistoryIndexRoute
  '/document-input-agent/': typeof SidebarDocumentInputAgentIndexRoute
  '/documents/': typeof SidebarDocumentsIndexRoute
  '/openai/': typeof SidebarOpenaiIndexRoute
  '/settings/': typeof SidebarSettingsIndexRoute
  '/template-agent/': typeof SidebarTemplateAgentIndexRoute
  '/template-variable-docs/': typeof SidebarTemplateVariableDocsIndexRoute
  '/template-variables/': typeof SidebarTemplateVariablesIndexRoute
  '/templates/': typeof SidebarTemplatesIndexRoute
  '/documents/$id/variables': typeof SidebarDocumentsIdVariablesRoute
  '/templates/$id/variables': typeof SidebarTemplatesIdVariablesRoute
  '/templates/new/variables': typeof SidebarTemplatesNewVariablesRoute
  '/dashboard/tickets/': typeof SidebarDashboardTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/docx-export-preview': typeof DocxExportPreviewRoute
  '/sign-in': typeof SignInRoute
  '/home': typeof SidebarHomeRoute
  '/document-input-agent-history/$userId': typeof SidebarDocumentInputAgentHistoryUserIdRoute
  '/documents/$id': typeof SidebarDocumentsIdRouteWithChildren
  '/documents/new': typeof SidebarDocumentsNewRoute
  '/template-variable-docs/$docId': typeof SidebarTemplateVariableDocsDocIdRoute
  '/template-variables/$id': typeof SidebarTemplateVariablesIdRoute
  '/template-variables/documents': typeof SidebarTemplateVariablesDocumentsRoute
  '/template-variables/excel': typeof SidebarTemplateVariablesExcelRoute
  '/template-variables/fields': typeof SidebarTemplateVariablesFieldsRoute
  '/template-variables/html-content': typeof SidebarTemplateVariablesHtmlContentRoute
  '/template-variables/image-form': typeof SidebarTemplateVariablesImageFormRoute
  '/template-variables/new': typeof SidebarTemplateVariablesNewRoute
  '/template-variables/powerpoint': typeof SidebarTemplateVariablesPowerpointRoute
  '/template-variables/settings': typeof SidebarTemplateVariablesSettingsRoute
  '/template-variables/tables': typeof SidebarTemplateVariablesTablesRoute
  '/templates/$id': typeof SidebarTemplatesIdRouteWithChildren
  '/templates/new': typeof SidebarTemplatesNewRouteWithChildren
  '/admin': typeof SidebarAdminIndexRoute
  '/dashboard': typeof SidebarDashboardIndexRoute
  '/document-input-agent-history': typeof SidebarDocumentInputAgentHistoryIndexRoute
  '/document-input-agent': typeof SidebarDocumentInputAgentIndexRoute
  '/documents': typeof SidebarDocumentsIndexRoute
  '/openai': typeof SidebarOpenaiIndexRoute
  '/settings': typeof SidebarSettingsIndexRoute
  '/template-agent': typeof SidebarTemplateAgentIndexRoute
  '/template-variable-docs': typeof SidebarTemplateVariableDocsIndexRoute
  '/template-variables': typeof SidebarTemplateVariablesIndexRoute
  '/templates': typeof SidebarTemplatesIndexRoute
  '/documents/$id/variables': typeof SidebarDocumentsIdVariablesRoute
  '/templates/$id/variables': typeof SidebarTemplatesIdVariablesRoute
  '/templates/new/variables': typeof SidebarTemplatesNewVariablesRoute
  '/dashboard/tickets': typeof SidebarDashboardTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/docx-export-preview': typeof DocxExportPreviewRoute
  '/sign-in': typeof SignInRoute
  '/_sidebar/home': typeof SidebarHomeRoute
  '/_sidebar/document-input-agent-history/$userId': typeof SidebarDocumentInputAgentHistoryUserIdRoute
  '/_sidebar/documents/$id': typeof SidebarDocumentsIdRouteWithChildren
  '/_sidebar/documents/new': typeof SidebarDocumentsNewRoute
  '/_sidebar/template-variable-docs/$docId': typeof SidebarTemplateVariableDocsDocIdRoute
  '/_sidebar/template-variables/$id': typeof SidebarTemplateVariablesIdRoute
  '/_sidebar/template-variables/documents': typeof SidebarTemplateVariablesDocumentsRoute
  '/_sidebar/template-variables/excel': typeof SidebarTemplateVariablesExcelRoute
  '/_sidebar/template-variables/fields': typeof SidebarTemplateVariablesFieldsRoute
  '/_sidebar/template-variables/html-content': typeof SidebarTemplateVariablesHtmlContentRoute
  '/_sidebar/template-variables/image-form': typeof SidebarTemplateVariablesImageFormRoute
  '/_sidebar/template-variables/new': typeof SidebarTemplateVariablesNewRoute
  '/_sidebar/template-variables/powerpoint': typeof SidebarTemplateVariablesPowerpointRoute
  '/_sidebar/template-variables/settings': typeof SidebarTemplateVariablesSettingsRoute
  '/_sidebar/template-variables/tables': typeof SidebarTemplateVariablesTablesRoute
  '/_sidebar/templates/$id': typeof SidebarTemplatesIdRouteWithChildren
  '/_sidebar/templates/new': typeof SidebarTemplatesNewRouteWithChildren
  '/_sidebar/admin/': typeof SidebarAdminIndexRoute
  '/_sidebar/dashboard/': typeof SidebarDashboardIndexRoute
  '/_sidebar/document-input-agent-history/': typeof SidebarDocumentInputAgentHistoryIndexRoute
  '/_sidebar/document-input-agent/': typeof SidebarDocumentInputAgentIndexRoute
  '/_sidebar/documents/': typeof SidebarDocumentsIndexRoute
  '/_sidebar/openai/': typeof SidebarOpenaiIndexRoute
  '/_sidebar/settings/': typeof SidebarSettingsIndexRoute
  '/_sidebar/template-agent/': typeof SidebarTemplateAgentIndexRoute
  '/_sidebar/template-variable-docs/': typeof SidebarTemplateVariableDocsIndexRoute
  '/_sidebar/template-variables/': typeof SidebarTemplateVariablesIndexRoute
  '/_sidebar/templates/': typeof SidebarTemplatesIndexRoute
  '/_sidebar/documents/$id/variables': typeof SidebarDocumentsIdVariablesRoute
  '/_sidebar/templates/$id/variables': typeof SidebarTemplatesIdVariablesRoute
  '/_sidebar/templates/new/variables': typeof SidebarTemplatesNewVariablesRoute
  '/_sidebar/dashboard/tickets/': typeof SidebarDashboardTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/docx-export-preview'
    | '/sign-in'
    | '/home'
    | '/document-input-agent-history/$userId'
    | '/documents/$id'
    | '/documents/new'
    | '/template-variable-docs/$docId'
    | '/template-variables/$id'
    | '/template-variables/documents'
    | '/template-variables/excel'
    | '/template-variables/fields'
    | '/template-variables/html-content'
    | '/template-variables/image-form'
    | '/template-variables/new'
    | '/template-variables/powerpoint'
    | '/template-variables/settings'
    | '/template-variables/tables'
    | '/templates/$id'
    | '/templates/new'
    | '/admin/'
    | '/dashboard/'
    | '/document-input-agent-history/'
    | '/document-input-agent/'
    | '/documents/'
    | '/openai/'
    | '/settings/'
    | '/template-agent/'
    | '/template-variable-docs/'
    | '/template-variables/'
    | '/templates/'
    | '/documents/$id/variables'
    | '/templates/$id/variables'
    | '/templates/new/variables'
    | '/dashboard/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/docx-export-preview'
    | '/sign-in'
    | '/home'
    | '/document-input-agent-history/$userId'
    | '/documents/$id'
    | '/documents/new'
    | '/template-variable-docs/$docId'
    | '/template-variables/$id'
    | '/template-variables/documents'
    | '/template-variables/excel'
    | '/template-variables/fields'
    | '/template-variables/html-content'
    | '/template-variables/image-form'
    | '/template-variables/new'
    | '/template-variables/powerpoint'
    | '/template-variables/settings'
    | '/template-variables/tables'
    | '/templates/$id'
    | '/templates/new'
    | '/admin'
    | '/dashboard'
    | '/document-input-agent-history'
    | '/document-input-agent'
    | '/documents'
    | '/openai'
    | '/settings'
    | '/template-agent'
    | '/template-variable-docs'
    | '/template-variables'
    | '/templates'
    | '/documents/$id/variables'
    | '/templates/$id/variables'
    | '/templates/new/variables'
    | '/dashboard/tickets'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/change-password'
    | '/docx-export-preview'
    | '/sign-in'
    | '/_sidebar/home'
    | '/_sidebar/document-input-agent-history/$userId'
    | '/_sidebar/documents/$id'
    | '/_sidebar/documents/new'
    | '/_sidebar/template-variable-docs/$docId'
    | '/_sidebar/template-variables/$id'
    | '/_sidebar/template-variables/documents'
    | '/_sidebar/template-variables/excel'
    | '/_sidebar/template-variables/fields'
    | '/_sidebar/template-variables/html-content'
    | '/_sidebar/template-variables/image-form'
    | '/_sidebar/template-variables/new'
    | '/_sidebar/template-variables/powerpoint'
    | '/_sidebar/template-variables/settings'
    | '/_sidebar/template-variables/tables'
    | '/_sidebar/templates/$id'
    | '/_sidebar/templates/new'
    | '/_sidebar/admin/'
    | '/_sidebar/dashboard/'
    | '/_sidebar/document-input-agent-history/'
    | '/_sidebar/document-input-agent/'
    | '/_sidebar/documents/'
    | '/_sidebar/openai/'
    | '/_sidebar/settings/'
    | '/_sidebar/template-agent/'
    | '/_sidebar/template-variable-docs/'
    | '/_sidebar/template-variables/'
    | '/_sidebar/templates/'
    | '/_sidebar/documents/$id/variables'
    | '/_sidebar/templates/$id/variables'
    | '/_sidebar/templates/new/variables'
    | '/_sidebar/dashboard/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRoute: typeof SidebarRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  DocxExportPreviewRoute: typeof DocxExportPreviewRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docx-export-preview': {
      id: '/docx-export-preview'
      path: '/docx-export-preview'
      fullPath: '/docx-export-preview'
      preLoaderRoute: typeof DocxExportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/home': {
      id: '/_sidebar/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof SidebarHomeRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/templates/': {
      id: '/_sidebar/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof SidebarTemplatesIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/': {
      id: '/_sidebar/template-variables/'
      path: '/template-variables'
      fullPath: '/template-variables/'
      preLoaderRoute: typeof SidebarTemplateVariablesIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variable-docs/': {
      id: '/_sidebar/template-variable-docs/'
      path: '/template-variable-docs'
      fullPath: '/template-variable-docs/'
      preLoaderRoute: typeof SidebarTemplateVariableDocsIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-agent/': {
      id: '/_sidebar/template-agent/'
      path: '/template-agent'
      fullPath: '/template-agent/'
      preLoaderRoute: typeof SidebarTemplateAgentIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/settings/': {
      id: '/_sidebar/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SidebarSettingsIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/openai/': {
      id: '/_sidebar/openai/'
      path: '/openai'
      fullPath: '/openai/'
      preLoaderRoute: typeof SidebarOpenaiIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/documents/': {
      id: '/_sidebar/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof SidebarDocumentsIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/document-input-agent/': {
      id: '/_sidebar/document-input-agent/'
      path: '/document-input-agent'
      fullPath: '/document-input-agent/'
      preLoaderRoute: typeof SidebarDocumentInputAgentIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/document-input-agent-history/': {
      id: '/_sidebar/document-input-agent-history/'
      path: '/document-input-agent-history'
      fullPath: '/document-input-agent-history/'
      preLoaderRoute: typeof SidebarDocumentInputAgentHistoryIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/dashboard/': {
      id: '/_sidebar/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof SidebarDashboardIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/admin/': {
      id: '/_sidebar/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof SidebarAdminIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/templates/new': {
      id: '/_sidebar/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof SidebarTemplatesNewRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/templates/$id': {
      id: '/_sidebar/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof SidebarTemplatesIdRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/tables': {
      id: '/_sidebar/template-variables/tables'
      path: '/template-variables/tables'
      fullPath: '/template-variables/tables'
      preLoaderRoute: typeof SidebarTemplateVariablesTablesRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/settings': {
      id: '/_sidebar/template-variables/settings'
      path: '/template-variables/settings'
      fullPath: '/template-variables/settings'
      preLoaderRoute: typeof SidebarTemplateVariablesSettingsRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/powerpoint': {
      id: '/_sidebar/template-variables/powerpoint'
      path: '/template-variables/powerpoint'
      fullPath: '/template-variables/powerpoint'
      preLoaderRoute: typeof SidebarTemplateVariablesPowerpointRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/new': {
      id: '/_sidebar/template-variables/new'
      path: '/template-variables/new'
      fullPath: '/template-variables/new'
      preLoaderRoute: typeof SidebarTemplateVariablesNewRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/image-form': {
      id: '/_sidebar/template-variables/image-form'
      path: '/template-variables/image-form'
      fullPath: '/template-variables/image-form'
      preLoaderRoute: typeof SidebarTemplateVariablesImageFormRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/html-content': {
      id: '/_sidebar/template-variables/html-content'
      path: '/template-variables/html-content'
      fullPath: '/template-variables/html-content'
      preLoaderRoute: typeof SidebarTemplateVariablesHtmlContentRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/fields': {
      id: '/_sidebar/template-variables/fields'
      path: '/template-variables/fields'
      fullPath: '/template-variables/fields'
      preLoaderRoute: typeof SidebarTemplateVariablesFieldsRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/excel': {
      id: '/_sidebar/template-variables/excel'
      path: '/template-variables/excel'
      fullPath: '/template-variables/excel'
      preLoaderRoute: typeof SidebarTemplateVariablesExcelRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/documents': {
      id: '/_sidebar/template-variables/documents'
      path: '/template-variables/documents'
      fullPath: '/template-variables/documents'
      preLoaderRoute: typeof SidebarTemplateVariablesDocumentsRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variables/$id': {
      id: '/_sidebar/template-variables/$id'
      path: '/template-variables/$id'
      fullPath: '/template-variables/$id'
      preLoaderRoute: typeof SidebarTemplateVariablesIdRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/template-variable-docs/$docId': {
      id: '/_sidebar/template-variable-docs/$docId'
      path: '/template-variable-docs/$docId'
      fullPath: '/template-variable-docs/$docId'
      preLoaderRoute: typeof SidebarTemplateVariableDocsDocIdRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/documents/new': {
      id: '/_sidebar/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof SidebarDocumentsNewRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/documents/$id': {
      id: '/_sidebar/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof SidebarDocumentsIdRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/document-input-agent-history/$userId': {
      id: '/_sidebar/document-input-agent-history/$userId'
      path: '/document-input-agent-history/$userId'
      fullPath: '/document-input-agent-history/$userId'
      preLoaderRoute: typeof SidebarDocumentInputAgentHistoryUserIdRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/dashboard/tickets/': {
      id: '/_sidebar/dashboard/tickets/'
      path: '/dashboard/tickets'
      fullPath: '/dashboard/tickets/'
      preLoaderRoute: typeof SidebarDashboardTicketsIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/templates/new/variables': {
      id: '/_sidebar/templates/new/variables'
      path: '/variables'
      fullPath: '/templates/new/variables'
      preLoaderRoute: typeof SidebarTemplatesNewVariablesRouteImport
      parentRoute: typeof SidebarTemplatesNewRoute
    }
    '/_sidebar/templates/$id/variables': {
      id: '/_sidebar/templates/$id/variables'
      path: '/variables'
      fullPath: '/templates/$id/variables'
      preLoaderRoute: typeof SidebarTemplatesIdVariablesRouteImport
      parentRoute: typeof SidebarTemplatesIdRoute
    }
    '/_sidebar/documents/$id/variables': {
      id: '/_sidebar/documents/$id/variables'
      path: '/variables'
      fullPath: '/documents/$id/variables'
      preLoaderRoute: typeof SidebarDocumentsIdVariablesRouteImport
      parentRoute: typeof SidebarDocumentsIdRoute
    }
  }
}

interface SidebarDocumentsIdRouteChildren {
  SidebarDocumentsIdVariablesRoute: typeof SidebarDocumentsIdVariablesRoute
}

const SidebarDocumentsIdRouteChildren: SidebarDocumentsIdRouteChildren = {
  SidebarDocumentsIdVariablesRoute: SidebarDocumentsIdVariablesRoute,
}

const SidebarDocumentsIdRouteWithChildren =
  SidebarDocumentsIdRoute._addFileChildren(SidebarDocumentsIdRouteChildren)

interface SidebarTemplatesIdRouteChildren {
  SidebarTemplatesIdVariablesRoute: typeof SidebarTemplatesIdVariablesRoute
}

const SidebarTemplatesIdRouteChildren: SidebarTemplatesIdRouteChildren = {
  SidebarTemplatesIdVariablesRoute: SidebarTemplatesIdVariablesRoute,
}

const SidebarTemplatesIdRouteWithChildren =
  SidebarTemplatesIdRoute._addFileChildren(SidebarTemplatesIdRouteChildren)

interface SidebarTemplatesNewRouteChildren {
  SidebarTemplatesNewVariablesRoute: typeof SidebarTemplatesNewVariablesRoute
}

const SidebarTemplatesNewRouteChildren: SidebarTemplatesNewRouteChildren = {
  SidebarTemplatesNewVariablesRoute: SidebarTemplatesNewVariablesRoute,
}

const SidebarTemplatesNewRouteWithChildren =
  SidebarTemplatesNewRoute._addFileChildren(SidebarTemplatesNewRouteChildren)

interface SidebarRouteChildren {
  SidebarHomeRoute: typeof SidebarHomeRoute
  SidebarDocumentInputAgentHistoryUserIdRoute: typeof SidebarDocumentInputAgentHistoryUserIdRoute
  SidebarDocumentsIdRoute: typeof SidebarDocumentsIdRouteWithChildren
  SidebarDocumentsNewRoute: typeof SidebarDocumentsNewRoute
  SidebarTemplateVariableDocsDocIdRoute: typeof SidebarTemplateVariableDocsDocIdRoute
  SidebarTemplateVariablesIdRoute: typeof SidebarTemplateVariablesIdRoute
  SidebarTemplateVariablesDocumentsRoute: typeof SidebarTemplateVariablesDocumentsRoute
  SidebarTemplateVariablesExcelRoute: typeof SidebarTemplateVariablesExcelRoute
  SidebarTemplateVariablesFieldsRoute: typeof SidebarTemplateVariablesFieldsRoute
  SidebarTemplateVariablesHtmlContentRoute: typeof SidebarTemplateVariablesHtmlContentRoute
  SidebarTemplateVariablesImageFormRoute: typeof SidebarTemplateVariablesImageFormRoute
  SidebarTemplateVariablesNewRoute: typeof SidebarTemplateVariablesNewRoute
  SidebarTemplateVariablesPowerpointRoute: typeof SidebarTemplateVariablesPowerpointRoute
  SidebarTemplateVariablesSettingsRoute: typeof SidebarTemplateVariablesSettingsRoute
  SidebarTemplateVariablesTablesRoute: typeof SidebarTemplateVariablesTablesRoute
  SidebarTemplatesIdRoute: typeof SidebarTemplatesIdRouteWithChildren
  SidebarTemplatesNewRoute: typeof SidebarTemplatesNewRouteWithChildren
  SidebarAdminIndexRoute: typeof SidebarAdminIndexRoute
  SidebarDashboardIndexRoute: typeof SidebarDashboardIndexRoute
  SidebarDocumentInputAgentHistoryIndexRoute: typeof SidebarDocumentInputAgentHistoryIndexRoute
  SidebarDocumentInputAgentIndexRoute: typeof SidebarDocumentInputAgentIndexRoute
  SidebarDocumentsIndexRoute: typeof SidebarDocumentsIndexRoute
  SidebarOpenaiIndexRoute: typeof SidebarOpenaiIndexRoute
  SidebarSettingsIndexRoute: typeof SidebarSettingsIndexRoute
  SidebarTemplateAgentIndexRoute: typeof SidebarTemplateAgentIndexRoute
  SidebarTemplateVariableDocsIndexRoute: typeof SidebarTemplateVariableDocsIndexRoute
  SidebarTemplateVariablesIndexRoute: typeof SidebarTemplateVariablesIndexRoute
  SidebarTemplatesIndexRoute: typeof SidebarTemplatesIndexRoute
  SidebarDashboardTicketsIndexRoute: typeof SidebarDashboardTicketsIndexRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarHomeRoute: SidebarHomeRoute,
  SidebarDocumentInputAgentHistoryUserIdRoute:
    SidebarDocumentInputAgentHistoryUserIdRoute,
  SidebarDocumentsIdRoute: SidebarDocumentsIdRouteWithChildren,
  SidebarDocumentsNewRoute: SidebarDocumentsNewRoute,
  SidebarTemplateVariableDocsDocIdRoute: SidebarTemplateVariableDocsDocIdRoute,
  SidebarTemplateVariablesIdRoute: SidebarTemplateVariablesIdRoute,
  SidebarTemplateVariablesDocumentsRoute:
    SidebarTemplateVariablesDocumentsRoute,
  SidebarTemplateVariablesExcelRoute: SidebarTemplateVariablesExcelRoute,
  SidebarTemplateVariablesFieldsRoute: SidebarTemplateVariablesFieldsRoute,
  SidebarTemplateVariablesHtmlContentRoute:
    SidebarTemplateVariablesHtmlContentRoute,
  SidebarTemplateVariablesImageFormRoute:
    SidebarTemplateVariablesImageFormRoute,
  SidebarTemplateVariablesNewRoute: SidebarTemplateVariablesNewRoute,
  SidebarTemplateVariablesPowerpointRoute:
    SidebarTemplateVariablesPowerpointRoute,
  SidebarTemplateVariablesSettingsRoute: SidebarTemplateVariablesSettingsRoute,
  SidebarTemplateVariablesTablesRoute: SidebarTemplateVariablesTablesRoute,
  SidebarTemplatesIdRoute: SidebarTemplatesIdRouteWithChildren,
  SidebarTemplatesNewRoute: SidebarTemplatesNewRouteWithChildren,
  SidebarAdminIndexRoute: SidebarAdminIndexRoute,
  SidebarDashboardIndexRoute: SidebarDashboardIndexRoute,
  SidebarDocumentInputAgentHistoryIndexRoute:
    SidebarDocumentInputAgentHistoryIndexRoute,
  SidebarDocumentInputAgentIndexRoute: SidebarDocumentInputAgentIndexRoute,
  SidebarDocumentsIndexRoute: SidebarDocumentsIndexRoute,
  SidebarOpenaiIndexRoute: SidebarOpenaiIndexRoute,
  SidebarSettingsIndexRoute: SidebarSettingsIndexRoute,
  SidebarTemplateAgentIndexRoute: SidebarTemplateAgentIndexRoute,
  SidebarTemplateVariableDocsIndexRoute: SidebarTemplateVariableDocsIndexRoute,
  SidebarTemplateVariablesIndexRoute: SidebarTemplateVariablesIndexRoute,
  SidebarTemplatesIndexRoute: SidebarTemplatesIndexRoute,
  SidebarDashboardTicketsIndexRoute: SidebarDashboardTicketsIndexRoute,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRoute: SidebarRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  DocxExportPreviewRoute: DocxExportPreviewRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
